# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-15 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=0, max_length=3, verbose_name='\u6559\u5e08\u5e74\u9f84'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u6559\u5e08\u540d\u79f0'),
        ),
    ]
