# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-13 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_notice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8bfe\u7a0b\u516c\u544a'),
        ),
    ]
