# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-14 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_video_learn_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='learn_times',
            new_name='video_times',
        ),
    ]
