# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-07 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170728_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u7ecf\u4f7f\u7528'),
        ),
    ]
