# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-25 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170923_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birday',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
